import 'dart:convert';

/// `dartograph setup`이 생성하는 Claude Code PostToolUse 훅 스크립트.
///
/// 편집된 파일이 `.dart`일 때만 `dartograph impact --changed`를 실행한다.
/// 발견(risk ≥ `--fail-on`)이면 종료 2로 에이전트에게 보고를 되돌리고,
/// 분석 실패는 작업을 막지 않도록 경고만 남긴다. MCP 호출·외부 서비스는
/// 없다 — PATH의 dartograph와 로컬 프로젝트만 쓴다.
const agentHookScript = r'''#!/bin/sh
# Generated by `dartograph setup --install`. Claude Code PostToolUse hook:
# runs an impact pre-check after each Dart file edit.
set -u

input=$(cat)
file=$(printf '%s' "$input" | sed -n \
  's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1)
case "$file" in
  *.dart) ;;
  *) exit 0 ;;
esac

root="${CLAUDE_PROJECT_DIR:-$PWD}"
rel="${file#"$root"/}"

tmp=$(mktemp "${TMPDIR:-/tmp}/dartograph-changes.XXXXXX") || exit 0
printf '["%s"]\n' "$rel" >"$tmp"
report=$(dartograph impact --changed "$tmp" --format text \
  --fail-on high --incremental .dartograph/cache "$root" 2>&1)
status=$?
rm -f "$tmp"

if [ "$status" -eq 1 ]; then
  printf '%s\n' "$report" >&2
  exit 2
fi
if [ "$status" -ne 0 ]; then
  printf 'dartograph impact could not run (exit %s): %s\n' \
    "$status" "$report" >&2
fi
exit 0
''';

/// `--install`이 쓰는 훅 스크립트의 `.claude/hooks` 기준 파일명이다.
const agentHookScriptName = 'dartograph-impact.sh';

/// 설정 스니펫에 새겨지는 훅 명령 문자열이다. Claude Code는 hook 설정의
/// `command`를 그대로 셸에 넘기므로 `$CLAUDE_PROJECT_DIR` 확장을 쓴다.
const agentHookCommand =
    '"\$CLAUDE_PROJECT_DIR"/.claude/hooks/$agentHookScriptName';

/// `PostToolUse` 목록에 추가하는 dartograph 훅 항목이다.
Map<String, Object?> _postToolUseEntry() => <String, Object?>{
      'matcher': 'Edit|MultiEdit|Write',
      'hooks': <Object?>[
        <String, Object?>{'type': 'command', 'command': agentHookCommand},
      ],
    };

/// 인쇄용 Claude Code `hooks` 설정 블록을 결정적 순서로 돌려준다.
String agentHookConfigJson() =>
    const JsonEncoder.withIndent('  ').convert(<String, Object?>{
      'hooks': <String, Object?>{
        'PostToolUse': <Object?>[_postToolUseEntry()],
      },
    });

/// 인쇄용 프로젝트 `.mcp.json` 문서를 결정적 순서로 돌려준다.
String agentMcpConfigJson() =>
    const JsonEncoder.withIndent('  ').convert(<String, Object?>{
      'mcpServers': <String, Object?>{
        'dartograph': <String, Object?>{
          'command': 'dartograph',
          'args': <String>['mcp'],
        },
      },
    });

Map<String, Object?> _decodeObject(String? existing) {
  if (existing == null) return <String, Object?>{};
  final decoded = jsonDecode(existing);
  if (decoded is! Map<String, Object?>) {
    throw const FormatException('not a JSON object');
  }
  return decoded;
}

/// 기존 `.claude/settings.json` 내용에 dartograph 훅 항목을 병합한다.
///
/// 이미 dartograph 훅이 등록돼 있으면 `null`을 돌려 건너뛴다. `hooks`가
/// 객체가 아니거나 `PostToolUse`가 목록이 아닌 기존 설정, 깨진 JSON은
/// [FormatException]을 던져 호출자가 파일을 보존하게 한다.
String? mergeClaudeSettings(String? existing) {
  final settings = _decodeObject(existing);
  final hooks = settings.putIfAbsent('hooks', () => <String, Object?>{});
  if (hooks is! Map<String, Object?>) {
    throw const FormatException('"hooks" is not a JSON object');
  }
  final postToolUse = hooks.putIfAbsent('PostToolUse', () => <Object?>[]);
  if (postToolUse is! List<Object?>) {
    throw const FormatException('"hooks.PostToolUse" is not a JSON array');
  }
  for (final entry in postToolUse) {
    if (entry is Map<String, Object?> &&
        jsonEncode(entry).contains(agentHookScriptName)) {
      return null;
    }
  }
  postToolUse.add(_postToolUseEntry());
  return '${const JsonEncoder.withIndent('  ').convert(settings)}\n';
}

/// 기존 `.mcp.json` 내용에 dartograph 서버 항목을 병합한다.
///
/// `dartograph` 항목이 이미 있으면 `force`일 때만 생성 내용으로 교체하고
/// 아니면 `null`을 돌린다. `mcpServers`가 객체가 아닌 기존 설정과 깨진
/// JSON은 [FormatException]을 던진다.
String? mergeMcpConfig(String? existing, {required bool force}) {
  final config = _decodeObject(existing);
  final servers = config.putIfAbsent('mcpServers', () => <String, Object?>{});
  if (servers is! Map<String, Object?>) {
    throw const FormatException('"mcpServers" is not a JSON object');
  }
  if (servers.containsKey('dartograph') && !force) return null;
  servers['dartograph'] = <String, Object?>{
    'command': 'dartograph',
    'args': <String>['mcp'],
  };
  return '${const JsonEncoder.withIndent('  ').convert(config)}\n';
}
