import 'dart:convert';

/// `dartograph setup`이 생성하는 Claude Code PostToolUse 훅 스크립트.
///
/// 편집된 파일이 `.dart`일 때만 `dartograph impact --changed`를 실행한다.
/// 발견(risk ≥ `--fail-on`)이면 종료 2로 에이전트에게 보고를 되돌린다.
/// 입력 파싱·실행 실패도 종료 2다 — 게이트가 못 돌았는데 조용히 통과시키면
/// 에이전트는 점검이 된 줄 알고 진행하므로 실패를 보이게 막는다.
/// MCP 호출·외부 서비스는 없다 — PATH의 dartograph와 로컬 프로젝트만 쓴다.
const agentHookScript = r'''#!/bin/sh
# Generated by `dartograph setup --install`. Claude Code PostToolUse hook:
# runs an impact pre-check after each Dart file edit.
set -u

input=$(cat)
# file_path는 JSON 값이다 — python3/jq로 해석하고, 둘 다 없으면 sed로
# 추출하되 이스케이프 잔여(`\`나 `"`)가 보이면 잘린 경로이므로 실패 처리한다.
file=""
parsed=0
if command -v python3 >/dev/null 2>&1; then
  file=$(printf '%s' "$input" | python3 -c \
    'import json,sys
print(json.load(sys.stdin).get("tool_input",{}).get("file_path") or "")' \
    2>/dev/null) && parsed=1
elif command -v jq >/dev/null 2>&1; then
  file=$(printf '%s' "$input" \
    | jq -r '.tool_input.file_path // empty' 2>/dev/null) && parsed=1
else
  file=$(printf '%s' "$input" | sed -n \
    's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1)
  case "$file" in
    *\\*|*\"*)
      # JSON 이스케이프 잔여가 보이면 잘린 경로다 — 그 경로로 게이트를
      # 우회하지 않게 파싱 실패로 둔다.
      file="" ;;
    "")
      # 입력에 file_path 마커가 있는데 빈 추출이면 파싱 실패다.
      case "$input" in *'"file_path"'*) ;; *) parsed=1 ;; esac ;;
    *) parsed=1 ;;
  esac
fi
if [ "$parsed" -eq 0 ]; then
  printf 'dartograph: hook input could not be parsed; impact check not run\n' >&2
  exit 2
fi
case "$file" in
  *.dart) ;;
  *) exit 0 ;;
esac

root="${CLAUDE_PROJECT_DIR:-$PWD}"
# 끝의 슬래시를 벗겨 "$root"/* 패턴이 항상 프로젝트 안 경로에 맞게 한다.
while [ "$root" != / ] && [ "${root%/}" != "$root" ]; do root="${root%/}"; done
case "$file" in
  "$root"/*) rel="${file#"$root"/}" ;;
  /*)
    # 다른 프로젝트 아래 파일은 이 프로젝트 그래프의 분석 대상이 아니다.
    printf 'dartograph: %s is outside %s; impact check skipped\n' \
      "$file" "$root" >&2
    exit 0
    ;;
  *) rel="$file" ;;
esac

tmp=$(mktemp "${TMPDIR:-/tmp}/dartograph-changes.XXXXXX") || {
  printf 'dartograph: mktemp failed; impact check not run\n' >&2
  exit 2
}
# 경로의 `\`와 `"`를 JSON 이스케이프해 변경 목록 문서를 깨지지 않게 한다.
escaped=$(printf '%s' "$rel" | sed 's/\\/\\\\/g; s/"/\\"/g')
printf '["%s"]\n' "$escaped" >"$tmp"
report=$(dartograph impact --changed "$tmp" --format text \
  --fail-on high --incremental .dartograph/cache "$root" 2>&1)
status=$?
rm -f "$tmp"

if [ "$status" -eq 1 ]; then
  printf '%s\n' "$report" >&2
  exit 2
fi
if [ "$status" -ne 0 ]; then
  printf 'dartograph impact could not run (exit %s): %s\n' \
    "$status" "$report" >&2
  exit 2
fi
exit 0
''';

/// `--install`이 쓰는 훅 스크립트의 `.claude/hooks` 기준 파일명이다.
const agentHookScriptName = 'dartograph-impact.sh';

/// 설정 스니펫에 새겨지는 훅 명령 문자열이다. Claude Code는 hook 설정의
/// `command`를 그대로 셸에 넘기므로 `$CLAUDE_PROJECT_DIR` 확장을 쓴다.
const agentHookCommand =
    '"\$CLAUDE_PROJECT_DIR"/.claude/hooks/$agentHookScriptName';

/// `PostToolUse` 목록에 추가하는 dartograph 훅 항목이다.
Map<String, Object?> _postToolUseEntry() => <String, Object?>{
  'matcher': 'Edit|MultiEdit|Write',
  'hooks': <Object?>[
    <String, Object?>{'type': 'command', 'command': agentHookCommand},
  ],
};

/// 인쇄용 Claude Code `hooks` 설정 블록을 결정적 순서로 돌려준다.
String agentHookConfigJson() =>
    const JsonEncoder.withIndent('  ').convert(<String, Object?>{
      'hooks': <String, Object?>{
        'PostToolUse': <Object?>[_postToolUseEntry()],
      },
    });

/// `setup --target`이 받는 에이전트 이름이다.
///
/// Claude Code는 ·설정·`.mcp.json`을 모두 다루고, 나머지는 MCP 서버 항목만
/// 만든다([_printSetup] 참조). Codex만 설정이 전역(`$CODEX_HOME/config.toml`)이다.
const setupTargetClaude = 'claude';

/// Cursor 프로젝트 `.cursor/mcp.json` 타깃이다.
const setupTargetCursor = 'cursor';

/// Codex 전역 `$CODEX_HOME/config.toml` 타깃이다.
const setupTargetCodex = 'codex';

/// opencode 프로젝트 `opencode.json` 타깃이다.
const setupTargetOpenCode = 'opencode';

/// 지원하는 타깃 이름 집합이다.
const setupTargets = <String>{
  setupTargetClaude,
  setupTargetCursor,
  setupTargetCodex,
  setupTargetOpenCode,
};

/// MCP 서버 한 항목이다. Claude Code `.mcp.json`·Cursor `.cursor/mcp.json`이
/// 같은 `command`/`args` 모양을 쓴다.
Map<String, Object?> _mcpServerEntry() => <String, Object?>{
  'command': 'dartograph',
  'args': <String>['mcp'],
};

/// opencode `mcp` 항목이다. 로컬 서버는 `command`가 배열이다.
Map<String, Object?> _openCodeServerEntry() => <String, Object?>{
  'type': 'local',
  'command': <String>['dartograph', 'mcp'],
  'enabled': true,
};

/// 인쇄용 프로젝트 `.mcp.json`(그리고 Cursor `.cursor/mcp.json`) 문서를
/// 결정적 순서로 돌려준다.
String agentMcpConfigJson() =>
    const JsonEncoder.withIndent('  ').convert(<String, Object?>{
      'mcpServers': <String, Object?>{'dartograph': _mcpServerEntry()},
    });

/// 인쇄용 opencode `opencode.json` 문서를 결정적 순서로 돌려준다.
String agentOpenCodeConfigJson() =>
    const JsonEncoder.withIndent('  ').convert(<String, Object?>{
      r'$schema': 'https://opencode.ai/config.json',
      'mcp': <String, Object?>{'dartograph': _openCodeServerEntry()},
    });

/// Codex 전역 `config.toml`에 넣을 dartograph MCP 블록이다.
///
/// Codex는 프로젝트 설정이 아니라 `$CODEX_HOME/config.toml`(기본
/// `~/.codex/config.toml`)의 `mcp_servers` 표만 읽는다.
const codexMcpTomlBlock = '''
[mcp_servers.dartograph]
command = "dartograph"
args = ["mcp"]
''';

final _codexTableHeader = RegExp(
  r'^\s*\[\s*mcp_servers\s*\.\s*dartograph\s*\]\s*(#.*)?$',
  multiLine: true,
);

/// dartograph를 `[mcp_servers.dartograph]` 표가 아닌 다른 모양으로 정의한
/// 흔적이다 — 점 키(`mcp_servers.dartograph.command = …`)·배열 표
/// (`[[mcp_servers.dartograph]]`)·따옴표 키·인라인 표. TOML은 같은 표를
/// 두 번 정의할 수 없어 이런 정의 위에 표를 덧붙이면 config.toml 전체가
/// 파싱 에러가 된다 — JSON 경로와 같이 실패로 돌린다.
final _codexForeignDefinition = RegExp(
  r'''^\s*(?:\[+\s*mcp_servers\s*\.\s*|mcp_servers\s*\.\s*|'''
  r'''mcp_servers\s*=\s*\{[^\n]*)["']?dartograph''',
  multiLine: true,
);

/// TOML 다중 행 문자열(`"""`·`'''`) 안쪽에 있는지 추적한다.
///
/// 문자열 안의 `[mcp_servers.dartograph]` 같은 행은 헤더가 아니라 값이다.
/// 구분자가 한 행에 홀수 번 나타나면 경계를 넘은 것으로 본다 — 따옴표
/// 이스케이프까지 해석하지 않는 단순 스캔이며, 오인은 내용 보존 방향으로만
/// 작동한다.
class _TomlStringTracker {
  String _marker = '';

  /// 다음 행이 문자열 안쪽에서 시작하는지다.
  bool get inside => _marker.isNotEmpty;

  /// 한 행을 소비해 문자열 경계를 갱신한다.
  void advance(String line) {
    if (_marker.isNotEmpty) {
      if ((line.split(_marker).length - 1).isOdd) _marker = '';
      return;
    }
    for (final candidate in const ['"""', "'''"]) {
      if ((line.split(candidate).length - 1).isOdd) {
        _marker = candidate;
        return;
      }
    }
  }
}

/// TOML 문서에서 다중 행 문자열 밖의 행만 돌려준다.
Iterable<String> _tomlDefinitionLines(String text) sync* {
  final strings = _TomlStringTracker();
  for (final line in text.split('\n')) {
    if (!strings.inside) yield line;
    strings.advance(line);
  }
}

bool _hasCodexBlock(String text) =>
    _tomlDefinitionLines(text).any(_codexTableHeader.hasMatch);

bool _hasForeignCodexDefinition(String text) =>
    _tomlDefinitionLines(text).any(_codexForeignDefinition.hasMatch);

/// TOML에서 dartograph 표 블록을 걷어낸다. 그 표의 키 줄은 다음 최상위
/// `[table]`을 만나거나 파일이 끝날 때까지 이어진다. 다른 표의 다중 행
/// 문자열 안에 표 모양 행이 있어도 값으로 보고 지우지 않는다.
String _stripCodexBlock(String text) {
  final remaining = <String>[];
  var skipping = false;
  final strings = _TomlStringTracker();
  for (final line in text.split('\n')) {
    if (strings.inside) {
      strings.advance(line);
      remaining.add(line);
      continue;
    }
    if (_codexTableHeader.hasMatch(line)) {
      skipping = true;
      continue;
    }
    if (skipping) {
      if (line.trimLeft().startsWith('[')) {
        skipping = false;
      } else {
        // 지워지는 블록 안의 행은 문자열 추적 대상이 아니다.
        continue;
      }
    }
    strings.advance(line);
    remaining.add(line);
  }
  while (remaining.isNotEmpty && remaining.last.trim().isEmpty) {
    remaining.removeLast();
  }
  return remaining.isEmpty ? '' : '${remaining.join('\n')}\n';
}

/// Codex `config.toml` 문자열에 dartograph MCP 블록을 병합한다.
///
/// 이미 있으면 `force`일 때만 표준 블록으로 교체하고 아니면 `null`을 돌린다.
/// TOML 전체를 해석하지 않고 표 블록만 다룬다 — 다른 표·키는 그대로 보존된다.
/// 표가 아닌 모양(점 키·배열 표·인라인 표)으로 적힌 dartograph 정의가 있으면
/// [FormatException]이다 — 덧붙이면 같은 표의 중복 정의로 파일 전체가 깨진다.
String? mergeCodexConfig(String? existing, {required bool force}) {
  final text = existing ?? '';
  if (_hasCodexBlock(text)) {
    if (!force) return null;
    return '${_stripCodexBlock(text)}$codexMcpTomlBlock';
  }
  if (_hasForeignCodexDefinition(text)) {
    throw const FormatException(
      'config.toml defines dartograph under mcp_servers in an unsupported '
      'shape — merge it into a [mcp_servers.dartograph] table or remove it',
    );
  }
  if (text.isEmpty) return codexMcpTomlBlock;
  final separator = text.endsWith('\n') ? '\n' : '\n\n';
  return '$text$separator$codexMcpTomlBlock';
}

/// Codex `config.toml` 문자열에서 dartograph MCP 블록을 제거한다.
///
/// 항목이 없으면 `null`이다. 남는 내용이 없으면 빈 문자열을 돌린다 — 호출자가
/// 파일을 지울지 정한다.
String? removeCodexConfig(String? existing) {
  if (existing == null || !_hasCodexBlock(existing)) return null;
  return _stripCodexBlock(existing);
}

/// `.claude/settings.json`에서 dartograph 훅 항목을 제거한다.
///
/// 없으면 `null`, `hooks` 모양이 다르면 [FormatException]이다. 빈 컨테이너는
/// 함께 지워 원래 설정을 최대한 되돌린다.
String? removeClaudeSettingsHook(String? existing) {
  final settings = _decodeObject(existing);
  final hooks = settings['hooks'];
  if (hooks is! Map<String, Object?>) {
    if (settings.containsKey('hooks') && hooks != null) {
      throw const FormatException('"hooks" is not a JSON object');
    }
    return null;
  }
  final postToolUse = hooks['PostToolUse'];
  if (postToolUse is! List) {
    if (hooks.containsKey('PostToolUse') && postToolUse != null) {
      throw const FormatException('"hooks.PostToolUse" is not a JSON array');
    }
    return null;
  }
  final before = postToolUse.length;
  postToolUse.removeWhere(
    (entry) =>
        entry is Map<String, Object?> &&
        jsonEncode(entry).contains(agentHookScriptName),
  );
  if (postToolUse.length == before) return null;
  if (postToolUse.isEmpty) hooks.remove('PostToolUse');
  if (hooks.isEmpty) settings.remove('hooks');
  return '${const JsonEncoder.withIndent('  ').convert(settings)}\n';
}

/// `mcpServers` 항목을 담는 JSON 설정(`.mcp.json`·`.cursor/mcp.json`)에서
/// dartograph 항목을 제거한다. 없으면 `null`, 모양이 다르면 [FormatException].
String? removeMcpServerEntry(String? existing) {
  final config = _decodeObject(existing);
  final servers = config['mcpServers'];
  if (servers is! Map<String, Object?>) {
    if (config.containsKey('mcpServers') && servers != null) {
      throw const FormatException('"mcpServers" is not a JSON object');
    }
    return null;
  }
  if (!servers.containsKey('dartograph')) return null;
  servers.remove('dartograph');
  if (servers.isEmpty) config.remove('mcpServers');
  return '${const JsonEncoder.withIndent('  ').convert(config)}\n';
}

/// opencode `opencode.json`에서 dartograph `mcp` 항목을 제거한다.
String? removeOpenCodeEntry(String? existing) {
  final config = _decodeObject(existing);
  final mcp = config['mcp'];
  if (mcp is! Map<String, Object?>) {
    if (config.containsKey('mcp') && mcp != null) {
      throw const FormatException('"mcp" is not a JSON object');
    }
    return null;
  }
  if (!mcp.containsKey('dartograph')) return null;
  mcp.remove('dartograph');
  if (mcp.isEmpty) config.remove('mcp');
  return '${const JsonEncoder.withIndent('  ').convert(config)}\n';
}

Map<String, Object?> _decodeObject(String? existing) {
  if (existing == null) return <String, Object?>{};
  final decoded = jsonDecode(existing);
  if (decoded is! Map<String, Object?>) {
    throw const FormatException('not a JSON object');
  }
  return decoded;
}

/// 기존 `.claude/settings.json` 내용에 dartograph 훅 항목을 병합한다.
///
/// 이미 dartograph 훅이 등록돼 있으면 `null`을 돌려 건너뛴다. `hooks`가
/// 객체가 아니거나 `PostToolUse`가 목록이 아닌 기존 설정, 깨진 JSON은
/// [FormatException]을 던져 호출자가 파일을 보존하게 한다.
String? mergeClaudeSettings(String? existing) {
  final settings = _decodeObject(existing);
  // null은 비어 있는 값으로 본다 — 명시적으로 지운 키를 오류로 거부하지 않는다.
  final hooks = settings['hooks'] ??= <String, Object?>{};
  if (hooks is! Map<String, Object?>) {
    throw const FormatException('"hooks" is not a JSON object');
  }
  final postToolUse = hooks['PostToolUse'] ??= <Object?>[];
  if (postToolUse is! List<Object?>) {
    throw const FormatException('"hooks.PostToolUse" is not a JSON array');
  }
  for (final entry in postToolUse) {
    if (entry is Map<String, Object?> &&
        jsonEncode(entry).contains(agentHookScriptName)) {
      return null;
    }
  }
  postToolUse.add(_postToolUseEntry());
  return '${const JsonEncoder.withIndent('  ').convert(settings)}\n';
}

/// 기존 `.mcp.json` 내용에 dartograph 서버 항목을 병합한다.
///
/// `dartograph` 항목이 이미 있으면 `force`일 때만 생성 내용으로 교체하고
/// 아니면 `null`을 돌린다. `mcpServers`가 객체가 아닌 기존 설정과 깨진
/// JSON은 [FormatException]을 던진다.
String? mergeMcpConfig(String? existing, {required bool force}) {
  final config = _decodeObject(existing);
  final servers = config['mcpServers'] ??= <String, Object?>{};
  if (servers is! Map<String, Object?>) {
    throw const FormatException('"mcpServers" is not a JSON object');
  }
  if (servers.containsKey('dartograph') && !force) return null;
  servers['dartograph'] = _mcpServerEntry();
  return '${const JsonEncoder.withIndent('  ').convert(config)}\n';
}

/// 기존 `opencode.json` 내용에 dartograph `mcp` 항목을 병합한다.
///
/// `dartograph` 항목이 이미 있으면 `force`일 때만 생성 내용으로 교체하고
/// 아니면 `null`을 돌린다. `mcp`가 객체가 아닌 기존 설정과 깨진 JSON은
/// [FormatException]을 던진다. 다른 전역 키는 그대로 보존한다.
String? mergeOpenCodeConfig(String? existing, {required bool force}) {
  final config = _decodeObject(existing);
  final mcp = config['mcp'] ??= <String, Object?>{};
  if (mcp is! Map<String, Object?>) {
    throw const FormatException('"mcp" is not a JSON object');
  }
  if (mcp.containsKey('dartograph') && !force) return null;
  mcp['dartograph'] = _openCodeServerEntry();
  return '${const JsonEncoder.withIndent('  ').convert(config)}\n';
}
