import 'dart:convert';

/// `dartograph setup`이 생성하는 Claude Code PostToolUse 훅 스크립트.
///
/// 편집된 파일이 `.dart`일 때만 `dartograph impact --changed`를 실행한다.
/// 발견(risk ≥ `--fail-on`)이면 종료 2로 에이전트에게 보고를 되돌린다.
/// 입력 파싱·실행 실패도 종료 2다 — 게이트가 못 돌았는데 조용히 통과시키면
/// 에이전트는 점검이 된 줄 알고 진행하므로 실패를 보이게 막는다.
/// MCP 호출·외부 서비스는 없다 — PATH의 dartograph와 로컬 프로젝트만 쓴다.
const agentHookScript = r'''#!/bin/sh
# Generated by `dartograph setup --install`. Claude Code PostToolUse hook:
# runs an impact pre-check after each Dart file edit.
set -u

input=$(cat)
# file_path는 JSON 값이다 — python3/jq로 해석하고, 둘 다 없으면 sed로
# 추출하되 이스케이프 잔여(`\`나 `"`)가 보이면 잘린 경로이므로 실패 처리한다.
file=""
parsed=0
if command -v python3 >/dev/null 2>&1; then
  file=$(printf '%s' "$input" | python3 -c \
    'import json,sys
print(json.load(sys.stdin).get("tool_input",{}).get("file_path") or "")' \
    2>/dev/null) && parsed=1
elif command -v jq >/dev/null 2>&1; then
  file=$(printf '%s' "$input" \
    | jq -r '.tool_input.file_path // empty' 2>/dev/null) && parsed=1
else
  file=$(printf '%s' "$input" | sed -n \
    's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1)
  case "$file" in
    *\\*|*\"*)
      # JSON 이스케이프 잔여가 보이면 잘린 경로다 — 그 경로로 게이트를
      # 우회하지 않게 파싱 실패로 둔다.
      file="" ;;
    "")
      # 입력에 file_path 마커가 있는데 빈 추출이면 파싱 실패다.
      case "$input" in *'"file_path"'*) ;; *) parsed=1 ;; esac ;;
    *) parsed=1 ;;
  esac
fi
if [ "$parsed" -eq 0 ]; then
  printf 'dartograph: hook input could not be parsed; impact check not run\n' >&2
  exit 2
fi
case "$file" in
  *.dart) ;;
  *) exit 0 ;;
esac

root="${CLAUDE_PROJECT_DIR:-$PWD}"
# 끝의 슬래시를 벗겨 "$root"/* 패턴이 항상 프로젝트 안 경로에 맞게 한다.
while [ "$root" != / ] && [ "${root%/}" != "$root" ]; do root="${root%/}"; done
case "$file" in
  "$root"/*) rel="${file#"$root"/}" ;;
  /*)
    # 다른 프로젝트 아래 파일은 이 프로젝트 그래프의 분석 대상이 아니다.
    printf 'dartograph: %s is outside %s; impact check skipped\n' \
      "$file" "$root" >&2
    exit 0
    ;;
  *) rel="$file" ;;
esac

tmp=$(mktemp "${TMPDIR:-/tmp}/dartograph-changes.XXXXXX") || {
  printf 'dartograph: mktemp failed; impact check not run\n' >&2
  exit 2
}
# 경로의 `\`와 `"`를 JSON 이스케이프해 변경 목록 문서를 깨지지 않게 한다.
escaped=$(printf '%s' "$rel" | sed 's/\\/\\\\/g; s/"/\\"/g')
printf '["%s"]\n' "$escaped" >"$tmp"
report=$(dartograph impact --changed "$tmp" --format text \
  --fail-on high --incremental .dartograph/cache "$root" 2>&1)
status=$?
rm -f "$tmp"

if [ "$status" -eq 1 ]; then
  printf '%s\n' "$report" >&2
  exit 2
fi
if [ "$status" -ne 0 ]; then
  printf 'dartograph impact could not run (exit %s): %s\n' \
    "$status" "$report" >&2
  exit 2
fi
exit 0
''';

/// `--install`이 쓰는 훅 스크립트의 `.claude/hooks` 기준 파일명이다.
const agentHookScriptName = 'dartograph-impact.sh';

/// 설정 스니펫에 새겨지는 훅 명령 문자열이다. Claude Code는 hook 설정의
/// `command`를 그대로 셸에 넘기므로 `$CLAUDE_PROJECT_DIR` 확장을 쓴다.
const agentHookCommand =
    '"\$CLAUDE_PROJECT_DIR"/.claude/hooks/$agentHookScriptName';

/// `PostToolUse` 목록에 추가하는 dartograph 훅 항목이다.
Map<String, Object?> _postToolUseEntry() => <String, Object?>{
  'matcher': 'Edit|MultiEdit|Write',
  'hooks': <Object?>[
    <String, Object?>{'type': 'command', 'command': agentHookCommand},
  ],
};

/// 인쇄용 Claude Code `hooks` 설정 블록을 결정적 순서로 돌려준다.
String agentHookConfigJson() =>
    const JsonEncoder.withIndent('  ').convert(<String, Object?>{
      'hooks': <String, Object?>{
        'PostToolUse': <Object?>[_postToolUseEntry()],
      },
    });

/// 인쇄용 프로젝트 `.mcp.json` 문서를 결정적 순서로 돌려준다.
String agentMcpConfigJson() =>
    const JsonEncoder.withIndent('  ').convert(<String, Object?>{
      'mcpServers': <String, Object?>{
        'dartograph': <String, Object?>{
          'command': 'dartograph',
          'args': <String>['mcp'],
        },
      },
    });

Map<String, Object?> _decodeObject(String? existing) {
  if (existing == null) return <String, Object?>{};
  final decoded = jsonDecode(existing);
  if (decoded is! Map<String, Object?>) {
    throw const FormatException('not a JSON object');
  }
  return decoded;
}

/// 기존 `.claude/settings.json` 내용에 dartograph 훅 항목을 병합한다.
///
/// 이미 dartograph 훅이 등록돼 있으면 `null`을 돌려 건너뛴다. `hooks`가
/// 객체가 아니거나 `PostToolUse`가 목록이 아닌 기존 설정, 깨진 JSON은
/// [FormatException]을 던져 호출자가 파일을 보존하게 한다.
String? mergeClaudeSettings(String? existing) {
  final settings = _decodeObject(existing);
  // null은 비어 있는 값으로 본다 — 명시적으로 지운 키를 오류로 거부하지 않는다.
  final hooks = settings['hooks'] ??= <String, Object?>{};
  if (hooks is! Map<String, Object?>) {
    throw const FormatException('"hooks" is not a JSON object');
  }
  final postToolUse = hooks['PostToolUse'] ??= <Object?>[];
  if (postToolUse is! List<Object?>) {
    throw const FormatException('"hooks.PostToolUse" is not a JSON array');
  }
  for (final entry in postToolUse) {
    if (entry is Map<String, Object?> &&
        jsonEncode(entry).contains(agentHookScriptName)) {
      return null;
    }
  }
  postToolUse.add(_postToolUseEntry());
  return '${const JsonEncoder.withIndent('  ').convert(settings)}\n';
}

/// 기존 `.mcp.json` 내용에 dartograph 서버 항목을 병합한다.
///
/// `dartograph` 항목이 이미 있으면 `force`일 때만 생성 내용으로 교체하고
/// 아니면 `null`을 돌린다. `mcpServers`가 객체가 아닌 기존 설정과 깨진
/// JSON은 [FormatException]을 던진다.
String? mergeMcpConfig(String? existing, {required bool force}) {
  final config = _decodeObject(existing);
  final servers = config['mcpServers'] ??= <String, Object?>{};
  if (servers is! Map<String, Object?>) {
    throw const FormatException('"mcpServers" is not a JSON object');
  }
  if (servers.containsKey('dartograph') && !force) return null;
  servers['dartograph'] = <String, Object?>{
    'command': 'dartograph',
    'args': <String>['mcp'],
  };
  return '${const JsonEncoder.withIndent('  ').convert(config)}\n';
}
